name: bank-marketing-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - azureml-defaults>=1.38.0
    - scikit-learn==1.0.2
    - xgboost==1.5.0
    - joblib==1.1.0
    - numpy==1.21.0
    - pandas==1.3.0
    - inference-schema[numpy-support]
